config:
  BinderHub:
    use_registry: true
    image_prefix: gcr.io/binderhub-366201/binder-dev-
    hub_url: https://hub.tg-ALLOCATION.projects.jetstream-cloud.org
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/tls-acme: "true"

  hosts:
    - binder.tg-ALLOCATION.projects.jetstream-cloud.org
  tls:
    - hosts:
      - binder.tg-ALLOCATION.projects.jetstream-cloud.org
      secretName: certmanager-tls-binderhub

jupyterhub:
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - hub.tg-ALLOCATION.projects.jetstream-cloud.org
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt"
    tls:
       - hosts:
          - hub.tg-ALLOCATION.projects.jetstream-cloud.org
         secretName: certmanager-tls-hub

# From https://github.com/jupyterhub/binderhub/issues/1228#issuecomment-743977017
dind:
  enabled: true
  daemonset:
    image:
      name: docker
      tag: 20.10.21-dind
    extraArgs:
      - --mtu
      - "1400"

imageCleaner:
  host:
    enabled: false
