apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: js-xxx-yyy.jetstream-cloud.org
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
#  tls:
#  - hosts:
#    - js-xxx-yyy.jetstream-cloud.org
#    secretName: certmanager-tls-grafana
