apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dask-zarr
  namespace: jhub
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: flaskapp
        envFrom:
            - secretRef:
                  name: awsconfig
        image: zonca/gateway-dask-zarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: jhub
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
