apiVersion: batch/v1
kind: CronJob
metadata:
  name: checkbackup
  namespace: jhub
spec:
  #schedule: "0 */6 * * *"
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: checkbackup
            image: restic/restic:0.13.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /scripts/backup_is_current.sh && wget -q --timeout 10 --tries 5 -O /dev/null https://hc-ping.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            envFrom:
            - secretRef:
               name: s3-secret
            volumeMounts:
            - name: scripts
              mountPath: /scripts
          volumes:
          - name: scripts
            configMap:
              name: monitorscripts
              defaultMode: 0744


